Hide_date_comment_block
Voog/design-madrid pull request #103
Opened 2020-08-10 18:38 UTC by entertthk

2020-08-12 08:17 UTC, siimha commented on layouts/blog_article.tpl
> +              <section class="post-bottom formatted cfx{% if show_article_comments == false %} hide-article-comments{% endif %}">
Siin võiks eemaldata kogu selle ala, kui kommentaare pole (hetkel on lihtsalt peidetud). See viga on mul jäänud varasemast juba sisse.
```
{% if editmode or show_article_comments == false %}
   <section class="post-bottom formatted cfx"{% if editmode and show_article_comments == false %} style="display: none;"{% endif %}>
      {% include "comment-form" %}
      {% include "comments" %}
   </section>
{% endif %}
```

Editori eelvaates saaks kasutada midagi sellist:
```
preview: function(data) {
  var $articleComment =$('.post-bottom');
  if (data.show_comments == true) {
    $articleComment.show());
  } else if (data.show_comments == false) {
    $articleComment.hide();
  }
}
```

2020-08-24 14:34 UTC, tanelj requested changes
Ok, but some code styling issues.

2020-08-24 14:34 UTC, tanelj commented on components/article-settings-editor.tpl
> +      var articleDataValues = {}
Wrong location for `;`. Should be:

```javascript
      var articleDataValues = {};
    {% endif %}
```

2020-08-24 14:34 UTC, tanelj commented on components/article-settings-editor.tpl
> +    {% endif %};
Wrong location for `;`. Should be:

```javascript
      var globalDataValues = {}
    {% endif %};
```

2020-08-24 14:34 UTC, tanelj commented on components/blog-settings-editor.tpl
> +    {% endif %};
Wron location for `;`. Should be:

```javascript
      var globalDataValues = {}
    {% endif %};
```

2020-08-24 14:34 UTC, tanelj commented on components/article-settings-editor.tpl
> +      {
Wrong indentation
```javascript
       },
      {
```

2020-08-24 14:34 UTC, tanelj commented on components/article-settings-editor.tpl
> +          },
Comma not needed here and next line.

2020-08-24 14:34 UTC, tanelj commented on components/article-settings-editor.tpl
> +        },
Comma not needed here and next line.

2020-08-24 14:34 UTC, tanelj commented on components/blog-settings-editor.tpl
> +      type: 'site',
Comma not needed.

2020-08-24 14:34 UTC, tanelj commented on components/blog-settings-editor.tpl
> +          },
Comma not needed.

2020-08-24 14:34 UTC, tanelj commented on components/blog-settings-editor.tpl
> +          },
Comma not needed here and next line.

2020-08-24 14:34 UTC, tanelj commented on layouts/blog___news.tpl
> +                  <time class="article-date{% if article_data_show_date_defined != true %} site-data{% endif %}{% if show_article_date == false %} hide-article-date{% endif %}" datetime="{{ article.c
Do not render `<time>` tag in public mode when `article_data_show_date_defined == false`

Should be:
```
{% if editmode or show_article_date == true %}
  <time ...
{% endif  %}
```

2020-08-26 13:22 UTC, tanelj requested changes
In some places should be `!= null` instead of `!== null` to take account `undefinde` value (default when data attribute has been not set).

2020-08-26 13:22 UTC, tanelj commented on components/article-settings-editor.tpl
> +    if (articleDataValues.show_comments !== null && articleDataValues.show_comments !== '') {
Should be `!= null` instead of `!== null` to take account `undefinde` value.

2020-08-26 13:22 UTC, tanelj commented on components/article-settings-editor.tpl
> +    } else if (globalDataValues.show_comments !== null && globalDataValues.show_comments !== '') {
Should be `!= null` instead of `!== null` to take account `undefinde` value.

2020-08-26 13:22 UTC, tanelj commented on components/article-settings-editor.tpl
> +    if (articleDataValues.show_date !== null && articleDataValues.show_date !== '') {
Should be `!= null` instead of `!== null` to take account `undefinde` value.

2020-08-26 13:22 UTC, tanelj commented on components/article-settings-editor.tpl
> +    } else if (globalDataValues.show_dates !== null && globalDataValues.show_dates !== '') {
Should be `!= null` instead of `!== null` to take account `undefinde` value.

2020-08-26 13:22 UTC, tanelj commented on components/blog-settings-editor.tpl
> +    if (globalDataValues.show_comments !== null && globalDataValues.show_comments !== '') {
Should be `!= null` instead of `!== null` to take account `undefinde` value.

2020-08-26 13:22 UTC, tanelj commented on components/blog-settings-editor.tpl
> +    if (globalDataValues.show_dates !== null && globalDataValues.show_dates !== '') {
Should be `!= null` instead of `!== null` to take account `undefinde` value.

2020-08-27 20:48 UTC, tanelj approved these changes

2020-08-31 13:52 UTC, siimha approved these changes
Hea töö!

2020-08-31 19:26 UTC, merged