Add auto-generated product layout
Voog/design-madrid pull request #112
Opened 2022-02-07 09:22 UTC by pxska

Adds an auto-generated product layout to the design based on the initial product layout. Also add a browser hack to render crispy images in Chrome.

Closes #111.

2022-02-07 14:01 UTC, tanelj approved these changes
Nice work!

2022-02-07 14:42 UTC, PeeterPaal requested changes
Overall looks good, but a few comments

2022-02-07 14:42 UTC, PeeterPaal commented on layouts/auto_generated_product.tpl
> +          {% endif %}
`submenu-for-current` is not needed as subpages cannot be added to auto-rendered product pages

2022-02-08 12:39 UTC, PeeterPaal approved these changes
Looking good!

2022-02-10 11:49 UTC, tanelj approved these changes
Nice work!

2022-02-10 12:20 UTC, PeeterPaal approved these changes
Looks nice!

2022-02-10 20:25 UTC, merged