Add and use self-hosted fonts
Voog/design-madrid pull request #121
Opened 2022-11-23 14:47 UTC by SSirjes

Add and use self hosted fonts to improve GDPR compliance.
Closes #120

2022-12-05 09:55 UTC, pxska approved these changes
One small comment, otherwise looks good!

2022-12-05 09:55 UTC, pxska commented on sources/stylesheets/_fonts.scss
> +@font-face {
Indentation in this file should be fixed: everything below this line should be indented two spaces to the left.

This file should also have an empty line at the end of the file (so GitHub wouldn't be mad at us).

2022-12-23 09:36 UTC, PeeterPaal approved these changes
Just a few remarks, but overall looks good!

2022-12-23 09:36 UTC, PeeterPaal commented on sources/stylesheets/_fonts.scss
> +}
These are actually not necessary, as this design only uses 400 (`normal`) and 700 (`bold`) font weights. But nothing will break by leaving them in :)

2022-12-23 09:36 UTC, PeeterPaal commented on sources/stylesheets/_fonts.scss
> +}
Previous comment also applies here.

2023-01-05 10:40 UTC, tanelj requested changes
Nice, but style.css is not updated.

2023-01-05 10:40 UTC, tanelj commented on stylesheets/main.css
> +  src: url("../assets/roboto-v30-vietnamese_latin-ext_greek-ext_greek_cyrillic-ext_cyrillic-300.woff") format("woff");
Roboto 300 and 500 rules are removed form source (.scss) files but are still present in style.css.

Please run `grunt`.

2023-01-09 07:06 UTC, tanelj approved these changes
Nice!

2023-01-09 13:13 UTC, PeeterPaal approved these changes

2023-01-09 13:15 UTC, merged